### PR TITLE
Changes for move to Monorepo

### PR DESCRIPTION
**Pull request by Danp2**

### CODE REVIEW

**Comment by willruss1** [comment]
This is what I get testing on my home setup after manually installing a couple of node modules it complained were missing...

[xo-update.log](https://github.com/Jarli01/xenorchestra_updater/files/1697394/xo-update.log)

**Comment by Danp2** [comment]
@willruss1 Looks like you previously ran the upgrade script when you encountered the code issues and then ran it again. Can you restore to prior snapshot and then try again.

What version of XO? What were the node errors?

**Comment by Jarli01** [comment]
Of course, take a snapshot of your XO installation before you trying again.

**Comment by willruss1** [comment]
The node errors were about missing modules, I apparently hadn't rebuilt in a while on this instance. It gets past the node modules part fine, so I think it's all straight there now. But I'm no node dev, so maybe I'm seeing / doing something wrong. 

```
root@kalliope:/opt# node -v
v7.6.0
root@kalliope:/opt# yarn version
yarn version v0.21.3
```

The attached is the output from an attempted clean build of XO 5.16, not an upgrade. This is on my labs at home, not in real use anywhere. I can destroy, recreate, whatever as much as needed here.

[xo-update_2.log](https://github.com/Jarli01/xenorchestra_updater/files/1697780/xo-update_2.log)

**Comment by Danp2** [comment]
You can't run this script to build a new VM. There's a separate script for that --
https://github.com/Jarli01/xenorchestra_installer

**Comment by willruss1** [comment]
I'm almost certain I've used the update script in the past to clean rebuild, like when the move to yarn was made. But I will defer to you, since you made it. I'm just a simple sysadmin. 

From my point of view, it's not building a VM, it's building a node app. I'm no developer, but I think I can read a bash script:

The installer sets up dependencies via apt packages, clones the app code from git, then `yarn build` in the cloned folder. It sets up the systemd service file and enables / starts it. Nothing complicated.

The upgrade one (at least the version in this PR) is less linear, but basically seems like it moves some folders to keep in line with changes upstream (if necessary), then after a `git fetch` to compare installed vs available versions and a pull to update the code it does the _exact same_ `yarn build` to (re)build the node app. It then modifies the .service file if necessary, and restarts the service.

It seems to me that it's this common `yarn build` part that's failing, but clearly I'm missing something in the difference between pulling from git and building to "install" vs pulling from the same git and building via the same process to "upgrade".

So kindly ignore all the previous, and I'll just build a new instance for my labs and wait for someone else to test this, like everyone else.

**Comment by Jarli01** [comment]
Will, the update is only capable of pulling down the git changes from the XO repo. The installer is what creates all of the directories.

Due to the complications at the time, we worked on an installer first (since that was what was required to begin using XO) and then said... well heck we need a great way to pull down the changes and thus made this script. 

The updater cannot install the required dependencies, your log even proves this.

**Comment by Jarli01** [comment]
Keeping the scripts separate is also a bit of key approach as things were changing frequently enough that having a single script to do everything was more headache then it is worth. 

Please install using the installation script, and once that is done, you'll be able to update with this one. 

Unfortunately we need someone with a current distro, yet old XO installation to confirm if this works. 

Thank you for support the effort.

**Comment by Danp2** [comment]
Looks like they are now moving xo-web as well...

**Pull request merged**
