### PR TITLE
Fix: Node LTS check

### PR DESCRIPTION
**Pull request by Danp2**
Only abort if user hasn't requested to update Node

### CODE REVIEW

**Comment by Jarli01** [comment]
It appears you accidentally pulled out the processor and ram checks as well for the minimums required..

**Comment by Danp2** [comment]
No. The code was confusing because it was running the initial checks, then skipping past all of the functions to the execute the line `main "$@"`. I moved the initial checks to occur within the Main function.

This allowed me to check the value of $NODE while validating the version of Node. $NODE is set within Main, so it couldn't be checked at the beginning of the script.

**Comment by Danp2** [comment]
I've successfully tested the change and it appears to work as designed. Just need to work out the merge conflict.

**Comment by Jarli01** [comment]
Opening in GHD, give me a moment

**Comment by Danp2** [comment]
I resolved the merge issue.

**Pull request merged**
